apiVersion: v1
kind: Secret
metadata:
    name: grafana-api-key
    namespace: monitoring
type: Opaque
data:
    # apiKey: ZXlKcklqb2laVGxuZDA1elkxaDVNbFZ4TTFwSVRHSk5SWFpCYVc1WlNsbG1NblI2TjI0aUxDSnVJam9pYldGemRXUWlMQ0pwWkNJNk1YMD0=
    apiKey: YWRtaW46YWRtaW4=
