# permissions for end users to view grafanadatasources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafanadatasource-viewer-role
rules:
- apiGroups:
  - openviz.openviz.dev
  resources:
  - grafanadatasources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openviz.openviz.dev
  resources:
  - grafanadatasources/status
  verbs:
  - get
